// all countries to select acceding to NewsApi
export const countries: { value: string; option: string }[] = [
  { value: "au", option: "Australia" },
  { value: "br", option: "Brazil" },
  { value: "ca", option: "Canada" },
  { value: "cn", option: "China" },
  { value: "eg", option: "Egypt" },
  { value: "fr", option: "France" },
  { value: "de", option: "Germany" },
  { value: "gr", option: "Greece" },
  { value: "hk", option: "Hong Kong" },
  { value: "in", option: "India" },
  { value: "ie", option: "Ireland" },
  { value: "il", option: "Israel" },
  { value: "it", option: "Italy" },
  { value: "jp", option: "Japan" },
  { value: "nl", option: "Netherlands" },
  { value: "no", option: "Norway" },
  { value: "pk", option: "Pakistan" },
  { value: "pe", option: "Peru" },
  { value: "ph", option: "Philippines" },
  { value: "pt", option: "Portugal" },
  { value: "ro", option: "Romania" },
  { value: "ru", option: "Russian Federation" },
  { value: "sg", option: "Singapore" },
  { value: "es", option: "Spain" },
  { value: "se", option: "Sweden" },
  { value: "ch", option: "Switzerland" },
  { value: "tw", option: "Taiwan" },
  { value: "ua", option: "Ukraine" },
  { value: "gb", option: "United Kingdom" },
  { value: "us", option: "United States" },
];

// all categories to select acceding to NewsApi
export const categories: { value: string; option: string }[] = [
  { value: "business", option: "Business" },
  { value: "entertainment", option: "Entertainment" },
  { value: "general", option: "General" },
  { value: "health", option: "Health" },
  { value: "science", option: "Science" },
  { value: "sports", option: "Sports" },
  { value: "technology", option: "Technology" },
  { value: "world", option: "World" },
  { value: "nation", option: "Nation" },
];

// all languages to select acceding to NewsApi
export const languages: { value: string; option: string }[] = [
  { value: "ar", option: "Arabic" },
  { value: "zh", option: "Chinese" },
  { value: "nl", option: "Dutch" },
  { value: "en", option: "English" },
  { value: "fr", option: "French" },
  { value: "de", option: "German" },
  { value: "el", option: "Greek" },
  { value: "he", option: "Hebrew" },
  { value: "hi", option: "Hindi" },
  { value: "it", option: "Italian" },
  { value: "ja", option: "Japanese" },
  { value: "ml", option: "Malayalam" },
  { value: "mr", option: "Marathi" },
  { value: "no", option: "Norwegian" },
  { value: "pt", option: "Portuguese" },
  { value: "ro", option: "Romanian" },
  { value: "ru", option: "Russian" },
  { value: "es", option: "Spanish" },
  { value: "sv", option: "Swedish" },
  { value: "ta", option: "Tamil" },
  { value: "te", option: "Telugu" },
  { value: "uk", option: "Ukrainian" },
];
