export const countries: { value: string; option: string }[] = [
    { value: "ae", option: "United Arab Emirates" },
    { value: "ar", option: "Argentina" },
    { value: "at", option: "Austria" },
    { value: "au", option: "Australia" },
    { value: "be", option: "Belgium" },
    { value: "bg", option: "Bulgaria" },
    { value: "br", option: "Brazil" },
    { value: "ch", option: "Switzerland" },
    { value: "cn", option: "China" },
    { value: "co", option: "Colombia" },
    { value: "cu", option: "Cuba" },
    { value: "cz", option: "Czech Republic" },
    { value: "de", option: "Germany" },
    { value: "eg", option: "Egypt" },
    { value: "fr", option: "France" },
    { value: "gb", option: "United Kingdom" },
    { value: "gr", option: "Greece" },
    { value: "hk", option: "Hong Kong" },
    { value: "hu", option: "Hungary" },
    { value: "id", option: "Indonesia" },
    { value: "ie", option: "Ireland" },
    { value: "il", option: "Israel" },
    { value: "in", option: "India" },
    { value: "it", option: "Italy" },
    { value: "jp", option: "Japan" },
    { value: "kr", option: "South Korea" },
    { value: "lt", option: "Lithuania" },
    { value: "lv", option: "Latvia" },
    { value: "ma", option: "Morocco" },
    { value: "mx", option: "Mexico" },
    { value: "my", option: "Malaysia" },
    { value: "ng", option: "Nigeria" },
    { value: "nl", option: "Netherlands" },
    { value: "no", option: "Norway" },
    { value: "nz", option: "New Zealand" },
    { value: "ph", option: "Philippines" },
    { value: "pl", option: "Poland" },
    { value: "pt", option: "Portugal" },
    { value: "ro", option: "Romania" },
    { value: "rs", option: "Serbia" },
    { value: "ru", option: "Russia" },
    { value: "sa", option: "Saudi Arabia" },
    { value: "se", option: "Sweden" },
    { value: "sg", option: "Singapore" },
    { value: "si", option: "Slovenia" },
    { value: "sk", option: "Slovakia" },
    { value: "th", option: "Thailand" },
    { value: "tr", option: "Turkey" },
    { value: "tw", option: "Taiwan" },
    { value: "ua", option: "Ukraine" },
    { value: "us", option: "United States" },
    { value: "ve", option: "Venezuela" },
    { value: "za", option: "South Africa" },
  ];
export const categories: { value: string; option: string }[] = [
    { value: "business", option: "Business" },
    { value: "entertainment", option: "Entertainment" },
    { value: "general", option: "General" },
    { value: "health", option: "Health" },
    { value: "science", option: "Science" },
    { value: "sports", option: "Sports" },
    { value: "technology", option: "Technology" },
  ];
export const languages: { value: string; option: string }[] = [
    { value: "ar", option: "Arabic" },
    { value: "de", option: "German" },
    { value: "en", option: "English" },
    { value: "es", option: "Spanish" },
    { value: "fr", option: "French" },
    { value: "he", option: "Hebrew" },
    { value: "it", option: "Italian" },
    { value: "nl", option: "Dutch" },
    { value: "no", option: "Norwegian" },
    { value: "pt", option: "Portuguese" },
    { value: "ru", option: "Russian" },
    { value: "sv", option: "Swedish" },
    { value: "ud", option: "Urdu" },
    { value: "zh", option: "Chinese" },
  ];